# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmedia', '0004_auto_20171128_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wineinstance',
            old_name='MyWine',
            new_name='owner',
        ),
    ]
